### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by sonersivri** [hermeslm/generator-jhipster-angular-datatables#1]
I install but cannot use the generator

yo jhipster-angular-datatables
Error jhipster-angular-datatables 

You don’t seem to have a generator with the name “jhipster-angular-datatables” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/. 
Install them with npm install generator-jhipster-angular-datatables.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators. 

If yo cannot find the generator, run yo doctor to troubleshoot your system.

**Comment by hermeslm** [comment]
It looks like issues with your computer settings but you can install this package locally to your project if nothing works, just clone this project into your computer and link using "npm link" as superuser in the cloned project root folder. Then you can use it in your project without any trouble. I hope it can help you.

I will be working on this issue for a real solution.
